name: schedule_search_and_job_peek
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # annotations
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

  # api utils
  dio: ^5.4.0
  web_socket_channel: ^2.4.0

  # caching
  shared_preferences: ^2.2.2

  # DI
  get_it: ^7.6.4
  injectable: ^2.3.2

  # functional
  fpdart: ^1.1.0

  # i18n
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  slang: ^3.28.0
  slang_flutter: ^3.28.0

  # icons
  cupertino_icons: ^1.0.6

  # image utils
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9

  # mocking
  http_mock_adapter: ^0.6.1

  # routing
  auto_route: ^7.8.4

  # state management
  flutter_bloc: ^8.1.3

  # UI helpers
  flutter_local_notifications: ^16.3.0
  flutter_screenutil: ^5.9.0

  # UI components
  bot_toast: ^4.1.3
  sliver_tools: ^0.2.12

  # utils
  internet_connection_checker_plus: ^2.1.0
  jwt_decoder: ^2.0.1
  logger: ^2.0.2+1
  package_info_plus: ^5.0.1
  path_provider: ^2.1.1
  url_launcher: ^6.2.2
  uuid: ^4.2.2
  validators: ^3.0.0

dev_dependencies:
  # code analyzers
  flutter_lints: ^3.0.1

  # generators
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1

  # testing
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  bloc_test: ^9.1.5
  mockito: ^5.4.4

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
